### ISSUE TITLE
No output devices found on Yosemite Patch

### ISSUE THREAD

**Issue by b1zZi** [rmc-team/osx-patcher#15] opened 2020-10-17 14:29 UTC
Good morning!
First of all, thanks for the patch.
I`m running Yosemite patch on a Macbook 4,1 with a 128gb SSD 4gb RAM.
It`s been running really smoothly so far, the only issue is that it does not identify the internal speakers. The brightness control does not work as well.
Any advices, tips or workarounds?
Thanks in advance

**Comment by julian-fairfax** [comment] 2020-10-18 15:20
Hi,
The issue with the brightness control is unfortunately normal and you can use Brightness Slider (which was automatically installed by the patcher) to perform a similar function. As for the internal speakers, they should work but if not I recommend running the patch tool again to see if that fixes it. Thanks for your support!

**Comment by b1zZi** [comment] 2020-10-19 18:52
Thanks for the quick reply!
By the time you answered I've already discovered the brightness patch, hehe
![IMG_20201019_153559550_HDR](https://user-images.githubusercontent.com/72941237/96497761-8a649380-1221-11eb-95b9-7b5a70ff1f3f.jpg)
I've sent a picture I took from the patch command I used on terminal after re-installing Yosemite (I also used disk utility to erase the SSD again and formated it to mac OS Journaled) and don't know if it has anything to do with the sound issue, assuming GeForce is about the video driver.
The result is the same for both "detected model" or manually selecting MacBook 4,1.
After the reinstall the "no output device found" issue is gone. Thanks again!

**Comment by julian-fairfax** [comment] 2020-10-19 19:05
I'm not sure what that's about but it's probably not doing anything. If the issue is gone, can I close this?

**Comment by b1zZi** [comment] 2020-10-19 19:06
Oh, yeah, of course!
Case solved, thank you!

**Comment by b1zZi** [comment] 2020-10-19 19:15
I'm sorry, now I kinda know what happened.
Did some updates from the app store and lost the sound output again.

**Comment by julian-fairfax** [comment] 2020-10-19 19:58
If you install system updates, you will have to run the patch tool again

**Closed by julian-fairfax** 2020-10-19 19:58 UTC
