### ISSUE TITLE
[BUG] - Installer hanging part way through boot on Macbook 2,1 installation Yosimite or El Capitan

### ISSUE THREAD

**Issue by wehi69** [rmc-team/osx-patcher#16] opened 2020-11-18 16:07 UTC
Installer hangs. In verbose mode can see it is just after network starts, text remains on screen and spinning beachball appears - I tried the same process for Yosemite and El Capitan.

1. Reboot into installer USB
2. Boot hangs

I followed and made installation USB for both Yosemite and El Capitan:
https://github.com/rmc-team/macos-downloader and https://github.com/rmc-team/osx-patcher

Installation is complited successfully - either Yosimite or El Capitan.
After installation I ran patch command in terminal from USB (for Yosemite and El Capitan)

I got the following error:
No such file or directory + ... /System/Library/Extensions/GeForce7xxxGLDriver.bundle 

MacOS 10.7.5
OSX patcher ver. 1.1.3

I found the same error in another post (https://github.com/rmc-team/osx-patcher/issues/4) which is not resolved or solution was provided.

Thank you in advance.

**Comment by julian-fairfax** [comment] 2020-11-18 16:19
As I said on there, I don't have a Mac mini (or MacBook2,1) myself, so there's nothing I can test. I closed it cause there’s nothing I can do to fix it right now. That error you mentioned is probably not the cause of the issue but I'll fix it and you could test the new version?

**Comment by wehi69** [comment] 2020-11-18 16:22
Yes, I can test when new patch will. e available. I can send you detailed
log if you want.

**Comment by wehi69** [comment] 2020-11-18 16:31
Not available to download. Can you check again if archive is available.

**Comment by wehi69** [comment] 2020-11-18 16:34
Now, is available. I will try to install El Capitan with new patch and let you know.

**Comment by wehi69** [comment] 2020-11-18 21:50
I tried with provided patcher but it seems that errors still persist:

![20201118_221108](https://user-images.githubusercontent.com/74670883/99592217-33a0d400-29f0-11eb-8fa7-5e966755b857.jpg)

![20201118_221441](https://user-images.githubusercontent.com/74670883/99592232-38fe1e80-29f0-11eb-989c-5d7bd294f781.jpg)

More than 30minutes and patching is stucked with message "Patching graphics drivers"...

**Comment by wehi69** [comment] 2020-11-18 22:15
I tried once more time with patch -v and please find more details:

![20201118_230314](https://user-images.githubusercontent.com/74670883/99594727-ddce2b00-29f3-11eb-9a73-de3586c481e8.jpg)

![20201118_230338](https://user-images.githubusercontent.com/74670883/99594734-e292df00-29f3-11eb-8dd5-50a9c255bcd4.jpg)

![20201118_230530](https://user-images.githubusercontent.com/74670883/99594740-e58dcf80-29f3-11eb-9309-cd606c72bb3f.jpg)

**Comment by julian-fairfax** [comment] 2020-11-19 06:07
Something is definitely wrong there. Could you try erasing your system drive and reinstalling?

**Comment by wehi69** [comment] 2020-11-19 07:57
I deleted all partitions and install from scratch:

![20201119_073610](https://user-images.githubusercontent.com/74670883/99636967-755b6a00-2a44-11eb-96d9-d84d82290e2e.jpg)

![20201119_073628](https://user-images.githubusercontent.com/74670883/99636975-78eef100-2a44-11eb-852a-b41970dc9b4c.jpg)

![20201119_073658](https://user-images.githubusercontent.com/74670883/99636981-7be9e180-2a44-11eb-87f1-0b06642d97ef.jpg)

![20201119_075943](https://user-images.githubusercontent.com/74670883/99636986-8015ff00-2a44-11eb-8503-b291adf611f2.jpg)

![20201119_080009](https://user-images.githubusercontent.com/74670883/99637013-8906d080-2a44-11eb-8d6e-79abd3a92e03.jpg)

![20201119_083308](https://user-images.githubusercontent.com/74670883/99637040-9623bf80-2a44-11eb-9822-ab844aa48f5f.jpg)

![20201119_083320](https://user-images.githubusercontent.com/74670883/99637073-9d4acd80-2a44-11eb-91f1-93d28709cb49.jpg)

![20201119_083624](https://user-images.githubusercontent.com/74670883/99637093-a471db80-2a44-11eb-8223-053b761b9964.jpg)

![20201119_083921](https://user-images.githubusercontent.com/74670883/99637155-bce1f600-2a44-11eb-823a-8d2820a25d0c.jpg)

![20201119_084010](https://user-images.githubusercontent.com/74670883/99637174-c4a19a80-2a44-11eb-90e3-546ab1cd89fc.jpg)

Boot of new installation El Cap is still not possible after patching. I tried different disks, I changed RAM and tried installation with different disks. Is any HW issue possible?

**Comment by wehi69** [comment] 2020-11-19 09:04
I tried and successfully installed Yosemite with new patch, but unfortunatelly it seems that patch is not working with El Capitan:

![image](https://user-images.githubusercontent.com/74670883/99644779-a345ac00-2a4e-11eb-8bbd-491995507b67.png)

**Comment by julian-fairfax** [comment] 2020-11-19 11:19
From my understanding it didn't work with El Capitan before either, but this change fixed Yosemite?

**Comment by wehi69** [comment] 2020-11-19 11:36
You are right - Yosemite didn't work before with old patcher 1.1.3, now
with the latest patch (which you mentioned in previous post) is working
properly.

Do you have any idea how can i resolve this issue with El Capitan? Do you
need any additional information or logs?

**Comment by julian-fairfax** [comment] 2020-11-19 12:26
You could send me the logs patch -v and maybe try booting the Mac in verbose mode but there's not much else I can do unfortunately. Well spotted on that (hopefully fixed) issue though 😉

**Comment by wehi69** [comment] 2020-11-19 12:55
I tried boot it in verbose mode:

![20201119_135008](https://user-images.githubusercontent.com/74670883/99669032-c84a1700-2a6e-11eb-8ac9-998fe24a2a07.jpg)

![20201119_135025](https://user-images.githubusercontent.com/74670883/99669046-cd0ecb00-2a6e-11eb-91a5-c6a40f772c97.jpg)

**Comment by wehi69** [comment] 2020-11-19 12:56
![20201119_135539](https://user-images.githubusercontent.com/74670883/99669177-fdef0000-2a6e-11eb-898a-3d626b931048.jpg)

**Comment by wehi69** [comment] 2020-11-19 13:36
Safe mode output:

![20201119_143541](https://user-images.githubusercontent.com/74670883/99673111-a5226600-2a74-11eb-95da-05d3dd839fd9.jpg)

**Comment by wehi69** [comment] 2020-11-19 14:43
Finally, i successfully resolved all issues:

![image](https://user-images.githubusercontent.com/74670883/99680689-a015e480-2a7d-11eb-92b3-cc1da379d442.png)

Solution: 
repair permissions in single user mode (sudo /usr/libexec/repair_packages --verify --standard-pkgs /), boot in verbose mode and normal reboot. 

Thank you for your time :)

**Comment by julian-fairfax** [comment] 2020-11-20 05:16
Well that's odd and I'm not sure if I could implement that, but I'm glad you got it working!

**Closed by julian-fairfax** 2020-11-20 05:16 UTC
Labels: bug
